### ISSUE TITLE
请求采用requests发送https请求时全局默认关闭ssl证书校验

### ISSUE THREAD

**Issue by hasunce** [eosmoto/eosiopy#10]
verify=False

**Comment by eosmoto** [comment]
done

**Comment by eosmoto** [comment]
Such changes can lead to block information error
nodeosd_1  | 1422761ms thread-0   http_plugin.cpp:406           handle_exception     ] Exception Details: 3010009 block_id_type_exception: Invalid block ID
nodeosd_1  | Invalid Block number or ID, must be greater than 0 and less than 64 characters
